name = "mafia-vip-bot"
main = "cloudflare_worker.js"
compatibility_date = "2024-12-01"

[env.production]
name = "mafia-vip-bot"
main = "cloudflare_worker.js"

[[env.production.kv_namespaces]]
binding = "FEEDBACK_STORE"
id = "c0343f8b59b74a61a29685102e0ec461"
